export const CATEGORIES = [
  "AI",
  "SaaS",
  "Legal Tech",
  "Consumer",
  "Developer Tools",
  "Health",
];

export const SEED_EVENTS = [
  {
    id: "evt_built_different",
    name: "Built Different: Auth0 × Stripe Hackathon",
    host: "Auth0 Events – San Francisco",
    dateLabel: "Thu, Jul 30",
    time: "12:00 PM – 7:30 PM PDT",
    location: "Okta, 100 1st St, San Francisco, CA",
    description:
      "Build a monetized, multi-user SaaS application from scratch using Stripe and Auth0. Judged live at the end of the build session.",
    prizes: [
      "1st: $2,000 Amazon gift card + $3,000 Stripe credits",
      "2nd: $1,000 Amazon gift card + $2,000 Stripe credits",
      "3rd: $500 Amazon gift card + $1,000 Stripe credits",
    ],
    schedule: [
      { time: "12:00 PM", label: "Lunch and team formation" },
      { time: "1:00 PM", label: "Build session begins" },
      { time: "5:30 PM", label: "Live project demos" },
      { time: "6:30 PM", label: "Winners announced" },
    ],
    submissionDeadline: "5:30 PM PDT",
    coverColor: "var(--accent-600)",
    status: "upcoming",
  },
  {
    id: "evt_product-lab",
    name: "Product Lab: AI for Good",
    host: "Product Lab – Oakland",
    dateLabel: "Sat, Aug 15",
    time: "9:00 AM – 6:00 PM PDT",
    location: "Oakland Tech Exchange, 55 Harrison St, Oakland, CA",
    description:
      "Create an AI-powered product that makes a measurable difference in education, accessibility, or community health.",
    prizes: [
      "1st: $3,000 cash + $2,000 cloud credits",
      "2nd: $1,500 cash + $1,000 cloud credits",
      "Community choice: $750 cash",
    ],
    schedule: [
      { time: "9:00 AM", label: "Check-in and challenge briefing" },
      { time: "10:00 AM", label: "Build session begins" },
      { time: "4:30 PM", label: "Project demos" },
      { time: "5:30 PM", label: "Awards and community vote" },
    ],
    submissionDeadline: "4:00 PM PDT",
    coverColor: "var(--accent-800)",
    status: "upcoming",
  },
  {
    id: "evt-ship-weekend",
    name: "Ship Weekend: Zero to Revenue",
    host: "Launch House – Remote",
    dateLabel: "Fri, Sep 11",
    time: "5:00 PM – 8:00 PM PDT",
    location: "Online · Live kickoff",
    description:
      "Turn a rough idea into a revenue-ready product over one focused weekend with mentors, customer interviews, and live demos.",
    prizes: [
      "1st: $2,500 Stripe credits + mentor office hours",
      "2nd: $1,000 Stripe credits + launch promotion",
      "Best demo: $500 cash",
    ],
    schedule: [
      { time: "5:00 PM", label: "Kickoff and team matching" },
      { time: "7:00 PM", label: "Customer discovery sprint" },
      { time: "Sat 6:00 PM", label: "Founder feedback sessions" },
      { time: "Sun 4:00 PM", label: "Final demos and judging" },
    ],
    submissionDeadline: "Sun, 2:00 PM PDT",
    coverColor: "var(--accent-500)",
    status: "upcoming",
  },
  {
    id: "evt-climate-build",
    name: "Climate Build Sprint",
    host: "Bay Area Climate Collective",
    dateLabel: "Sat, Jun 20",
    time: "10:00 AM – 5:00 PM PDT",
    location: "The Greenhouse, 410 14th St, San Francisco, CA",
    description:
      "Build practical software for tracking emissions, coordinating climate action, or helping people make lower-impact choices.",
    prizes: [
      "1st: $2,000 grant + climate mentor sessions",
      "2nd: $1,000 grant",
      "Best open-source contribution: $500 grant",
    ],
    schedule: [
      { time: "10:00 AM", label: "Climate data briefing" },
      { time: "11:00 AM", label: "Build session begins" },
      { time: "3:30 PM", label: "Demos and impact review" },
      { time: "4:30 PM", label: "Winners announced" },
    ],
    submissionDeadline: "3:30 PM PDT",
    coverColor: "var(--neutral-700)",
    status: "past",
  },
];

export const STATUS_LABELS = {
  submitted: "Submitted",
  queued: "Queued",
  reviewing: "Reviewing",
  completed: "Completed",
  needs_attention: "Needs Attention",
  failed: "Failed",
};

const now = new Date("2026-07-30T18:00:00Z").toISOString();

export const SEED_PROJECTS = [
  {
    id: "sub_seed_1",
    name: "AI Legal Editor",
    productUrl: "https://ai-legal-editor.example.com",
    instructions: "Focus on the contract redline flow in the demo account.",
    category: "Legal Tech",
    eventId: "evt_built_different",
    status: "submitted",
    tagline: "Judging starts tonight",
    coverColor: "var(--accent-500)",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sub_seed_2",
    name: "Tennis Match Platform",
    productUrl: "https://tennismatch.example.com",
    instructions: "Try the matchmaking flow with two accounts.",
    category: "Consumer",
    eventId: "evt_built_different",
    status: "reviewing",
    tagline: "Results soon",
    coverColor: "var(--accent-700)",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sub_seed_3",
    name: "DevTools Monitor",
    productUrl: "https://devtools-monitor.example.com",
    instructions: "Check the live error stream on the dashboard.",
    category: "Developer Tools",
    eventId: "evt_built_different",
    status: "completed",
    tagline: "Results published",
    coverColor: "var(--neutral-700)",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sub_seed_4",
    name: "Pulse Health Tracker",
    productUrl: "https://pulse-health.example.com",
    instructions: "Look at the weekly trends chart for a seeded user.",
    category: "Health",
    eventId: "evt_built_different",
    status: "submitted",
    tagline: "Awaiting review",
    coverColor: "var(--accent-300)",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sub_seed_5",
    name: "Ledger SaaS",
    productUrl: "https://ledger-saas.example.com",
    instructions: "Invite flow is under Settings > Team.",
    category: "SaaS",
    eventId: "evt_built_different",
    status: "queued",
    tagline: "Queued for review",
    coverColor: "var(--accent-800)",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sub_seed_6",
    name: "Focus AI Copilot",
    productUrl: "https://focus-copilot.example.com",
    instructions: "Ask it to summarize a long doc for the best demo.",
    category: "AI",
    eventId: "evt_built_different",
    status: "submitted",
    tagline: "Awaiting review",
    coverColor: "var(--accent-600)",
    createdAt: now,
    updatedAt: now,
  },
];
